#!/bin/bash

aws sns publish --topic-arn arn:aws:sns:eu-central-1:055951622116:test-topic-simple --message "{ \"msg\": \"hello 1\" }" &
aws sns publish --topic-arn arn:aws:sns:eu-central-1:055951622116:test-topic-simple --message "{ \"msg\": \"hello 2\" }" &
aws sns publish --topic-arn arn:aws:sns:eu-central-1:055951622116:test-topic-simple --message "{ \"msg\": \"hello 3\" }" &
aws sns publish --topic-arn arn:aws:sns:eu-central-1:055951622116:test-topic-simple --message "{ \"msg\": \"hello 4\" }" &
aws sns publish --topic-arn arn:aws:sns:eu-central-1:055951622116:test-topic-simple --message "{ \"msg\": \"hello 5\" }" &
aws sns publish --topic-arn arn:aws:sns:eu-central-1:055951622116:test-topic-simple --message "{ \"msg\": \"hello 6\" }" &

wait